package ann

import (
	"encoding/json"
	"errors"
	"github.com/ashraf/consensa/internal/vector"
	"sort"
)

// Mutation is the deterministic payload a Raft entry carries for one graph operation.
// Replicas apply it in log order, so their graph topology does not depend on local timing.
type Mutation struct {
	Operation string        `json:"operation"`
	ID        string        `json:"id"`
	Vector    vector.Vector `json:"vector,omitempty"`
}

// EncodeMutation serializes a validated insertion for a Raft log entry.
func EncodeMutation(id string, v vector.Vector) ([]byte, error) {
	return json.Marshal(Mutation{Operation: "insert", ID: id, Vector: v})
}

// EncodeDeleteMutation serializes a replicated graph deletion.
func EncodeDeleteMutation(id string) ([]byte, error) {
	return json.Marshal(Mutation{Operation: "delete", ID: id})
}

// ApplyMutation decodes and applies one Raft-ordered graph mutation.
func (h *HNSW) ApplyMutation(data []byte) error {
	var m Mutation
	if err := json.Unmarshal(data, &m); err != nil {
		return err
	}
	switch m.Operation {
	case "insert":
		return h.Insert(m.ID, m.Vector)
	case "delete":
		return h.Delete(m.ID)
	default:
		return errors.New("ann: unknown graph mutation")
	}
}

type snapshotNode struct {
	ID        string
	Vector    vector.Vector
	Level     int
	Neighbors map[int][]string
}
type snapshot struct {
	Config   Config
	Entry    string
	MaxLevel int
	Nodes    []snapshotNode
}

// Snapshot returns a canonical byte representation. Sorting map-derived node IDs makes
// snapshots comparable across replicas and lets tests detect accidental nondeterminism.
func (h *HNSW) Snapshot() ([]byte, error) {
	ids := make([]string, 0, len(h.nodes))
	for id := range h.nodes {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	s := snapshot{Config: h.cfg, Entry: h.entry, MaxLevel: h.maxLevel}
	for _, id := range ids {
		n := h.nodes[id]
		nn := map[int][]string{}
		for l, ns := range n.neighbors {
			nn[l] = append([]string(nil), ns...)
			sort.Strings(nn[l])
		}
		s.Nodes = append(s.Nodes, snapshotNode{ID: n.id, Vector: n.v, Level: n.level, Neighbors: nn})
	}
	return json.Marshal(s)
}

// Restore replaces the current graph with a snapshot previously generated by Snapshot.
func (h *HNSW) Restore(data []byte) error {
	var s snapshot
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	fresh, err := NewHNSW(s.Config)
	if err != nil {
		return err
	}
	fresh.entry = s.Entry
	fresh.maxLevel = s.MaxLevel
	for _, sn := range s.Nodes {
		fresh.nodes[sn.ID] = &node{id: sn.ID, v: append(vector.Vector(nil), sn.Vector...), level: sn.Level, neighbors: sn.Neighbors}
	}
	*h = *fresh
	return nil
}
