// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.36.0
// source: api/consensa/v1/consensa.proto

package consensav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertRequest) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type UpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertResponse) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Vector                `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Ef            uint32                 `protobuf:"varint,3,opt,name=ef,proto3" json:"ef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() *Vector {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetEf() uint32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{6}
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       map[string]*Vector     `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetResponse) GetVectors() map[string]*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{9}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type TransactionalPutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// txn_id must be unique per transaction; the caller picks it (a UUID, typically) since
	// only the caller knows whether a retried call is the same transaction or a new one.
	TxnId         string            `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Writes        map[string][]byte `protobuf:"bytes,2,rep,name=writes,proto3" json:"writes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionalPutRequest) Reset() {
	*x = TransactionalPutRequest{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionalPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionalPutRequest) ProtoMessage() {}

func (x *TransactionalPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionalPutRequest.ProtoReflect.Descriptor instead.
func (*TransactionalPutRequest) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionalPutRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TransactionalPutRequest) GetWrites() map[string][]byte {
	if x != nil {
		return x.Writes
	}
	return nil
}

type TransactionalPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionalPutResponse) Reset() {
	*x = TransactionalPutResponse{}
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionalPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionalPutResponse) ProtoMessage() {}

func (x *TransactionalPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_consensa_v1_consensa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionalPutResponse.ProtoReflect.Descriptor instead.
func (*TransactionalPutResponse) Descriptor() ([]byte, []int) {
	return file_api_consensa_v1_consensa_proto_rawDescGZIP(), []int{12}
}

var File_api_consensa_v1_consensa_proto protoreflect.FileDescriptor

const file_api_consensa_v1_consensa_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/consensa/v1/consensa.proto\x12\vconsensa.v1\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"L\n" +
	"\rUpsertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x06vector\x18\x02 \x01(\v2\x13.consensa.v1.VectorR\x06vector\",\n" +
	"\x0eUpsertResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\"X\n" +
	"\rSearchRequest\x12)\n" +
	"\x05query\x18\x01 \x01(\v2\x13.consensa.v1.VectorR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x0e\n" +
	"\x02ef\x18\x03 \x01(\rR\x02ef\":\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"#\n" +
	"\x0fBatchGetRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xa9\x01\n" +
	"\x10BatchGetResponse\x12D\n" +
	"\avectors\x18\x01 \x03(\v2*.consensa.v1.BatchGetResponse.VectorsEntryR\avectors\x1aO\n" +
	"\fVectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.consensa.v1.VectorR\x05value:\x028\x01\"\x0f\n" +
	"\rStatusRequest\"8\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\"\xb5\x01\n" +
	"\x17TransactionalPutRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12H\n" +
	"\x06writes\x18\x02 \x03(\v20.consensa.v1.TransactionalPutRequest.WritesEntryR\x06writes\x1a9\n" +
	"\vWritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x1a\n" +
	"\x18TransactionalPutResponse2\xe1\x02\n" +
	"\bConsensa\x12C\n" +
	"\x06Upsert\x12\x1a.consensa.v1.UpsertRequest\x1a\x1b.consensa.v1.UpsertResponse(\x01\x12A\n" +
	"\x06Search\x12\x1a.consensa.v1.SearchRequest\x1a\x19.consensa.v1.SearchResult0\x01\x12A\n" +
	"\x06Delete\x12\x1a.consensa.v1.DeleteRequest\x1a\x1b.consensa.v1.DeleteResponse\x12G\n" +
	"\bBatchGet\x12\x1c.consensa.v1.BatchGetRequest\x1a\x1d.consensa.v1.BatchGetResponse\x12A\n" +
	"\x06Status\x12\x1a.consensa.v1.StatusRequest\x1a\x1b.consensa.v1.StatusResponse2m\n" +
	"\n" +
	"ConsensaKV\x12_\n" +
	"\x10TransactionalPut\x12$.consensa.v1.TransactionalPutRequest\x1a%.consensa.v1.TransactionalPutResponseB7Z5github.com/ashraf/consensa/api/consensa/v1;consensav1b\x06proto3"

var (
	file_api_consensa_v1_consensa_proto_rawDescOnce sync.Once
	file_api_consensa_v1_consensa_proto_rawDescData []byte
)

func file_api_consensa_v1_consensa_proto_rawDescGZIP() []byte {
	file_api_consensa_v1_consensa_proto_rawDescOnce.Do(func() {
		file_api_consensa_v1_consensa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_consensa_v1_consensa_proto_rawDesc), len(file_api_consensa_v1_consensa_proto_rawDesc)))
	})
	return file_api_consensa_v1_consensa_proto_rawDescData
}

var file_api_consensa_v1_consensa_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_consensa_v1_consensa_proto_goTypes = []any{
	(*Vector)(nil),                   // 0: consensa.v1.Vector
	(*UpsertRequest)(nil),            // 1: consensa.v1.UpsertRequest
	(*UpsertResponse)(nil),           // 2: consensa.v1.UpsertResponse
	(*SearchRequest)(nil),            // 3: consensa.v1.SearchRequest
	(*SearchResult)(nil),             // 4: consensa.v1.SearchResult
	(*DeleteRequest)(nil),            // 5: consensa.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 6: consensa.v1.DeleteResponse
	(*BatchGetRequest)(nil),          // 7: consensa.v1.BatchGetRequest
	(*BatchGetResponse)(nil),         // 8: consensa.v1.BatchGetResponse
	(*StatusRequest)(nil),            // 9: consensa.v1.StatusRequest
	(*StatusResponse)(nil),           // 10: consensa.v1.StatusResponse
	(*TransactionalPutRequest)(nil),  // 11: consensa.v1.TransactionalPutRequest
	(*TransactionalPutResponse)(nil), // 12: consensa.v1.TransactionalPutResponse
	nil,                              // 13: consensa.v1.BatchGetResponse.VectorsEntry
	nil,                              // 14: consensa.v1.TransactionalPutRequest.WritesEntry
}
var file_api_consensa_v1_consensa_proto_depIdxs = []int32{
	0,  // 0: consensa.v1.UpsertRequest.vector:type_name -> consensa.v1.Vector
	0,  // 1: consensa.v1.SearchRequest.query:type_name -> consensa.v1.Vector
	13, // 2: consensa.v1.BatchGetResponse.vectors:type_name -> consensa.v1.BatchGetResponse.VectorsEntry
	14, // 3: consensa.v1.TransactionalPutRequest.writes:type_name -> consensa.v1.TransactionalPutRequest.WritesEntry
	0,  // 4: consensa.v1.BatchGetResponse.VectorsEntry.value:type_name -> consensa.v1.Vector
	1,  // 5: consensa.v1.Consensa.Upsert:input_type -> consensa.v1.UpsertRequest
	3,  // 6: consensa.v1.Consensa.Search:input_type -> consensa.v1.SearchRequest
	5,  // 7: consensa.v1.Consensa.Delete:input_type -> consensa.v1.DeleteRequest
	7,  // 8: consensa.v1.Consensa.BatchGet:input_type -> consensa.v1.BatchGetRequest
	9,  // 9: consensa.v1.Consensa.Status:input_type -> consensa.v1.StatusRequest
	11, // 10: consensa.v1.ConsensaKV.TransactionalPut:input_type -> consensa.v1.TransactionalPutRequest
	2,  // 11: consensa.v1.Consensa.Upsert:output_type -> consensa.v1.UpsertResponse
	4,  // 12: consensa.v1.Consensa.Search:output_type -> consensa.v1.SearchResult
	6,  // 13: consensa.v1.Consensa.Delete:output_type -> consensa.v1.DeleteResponse
	8,  // 14: consensa.v1.Consensa.BatchGet:output_type -> consensa.v1.BatchGetResponse
	10, // 15: consensa.v1.Consensa.Status:output_type -> consensa.v1.StatusResponse
	12, // 16: consensa.v1.ConsensaKV.TransactionalPut:output_type -> consensa.v1.TransactionalPutResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_consensa_v1_consensa_proto_init() }
func file_api_consensa_v1_consensa_proto_init() {
	if File_api_consensa_v1_consensa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_consensa_v1_consensa_proto_rawDesc), len(file_api_consensa_v1_consensa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_consensa_v1_consensa_proto_goTypes,
		DependencyIndexes: file_api_consensa_v1_consensa_proto_depIdxs,
		MessageInfos:      file_api_consensa_v1_consensa_proto_msgTypes,
	}.Build()
	File_api_consensa_v1_consensa_proto = out.File
	file_api_consensa_v1_consensa_proto_goTypes = nil
	file_api_consensa_v1_consensa_proto_depIdxs = nil
}
