// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/consensa/v1/consensa.proto

package consensav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Consensa_Upsert_FullMethodName   = "/consensa.v1.Consensa/Upsert"
	Consensa_Search_FullMethodName   = "/consensa.v1.Consensa/Search"
	Consensa_Delete_FullMethodName   = "/consensa.v1.Consensa/Delete"
	Consensa_BatchGet_FullMethodName = "/consensa.v1.Consensa/BatchGet"
	Consensa_Status_FullMethodName   = "/consensa.v1.Consensa/Status"
)

// ConsensaClient is the client API for Consensa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsensaClient interface {
	Upsert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpsertRequest, UpsertResponse], error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type consensaClient struct {
	cc grpc.ClientConnInterface
}

func NewConsensaClient(cc grpc.ClientConnInterface) ConsensaClient {
	return &consensaClient{cc}
}

func (c *consensaClient) Upsert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpsertRequest, UpsertResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Consensa_ServiceDesc.Streams[0], Consensa_Upsert_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpsertRequest, UpsertResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consensa_UpsertClient = grpc.ClientStreamingClient[UpsertRequest, UpsertResponse]

func (c *consensaClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Consensa_ServiceDesc.Streams[1], Consensa_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consensa_SearchClient = grpc.ServerStreamingClient[SearchResult]

func (c *consensaClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Consensa_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensaClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, Consensa_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consensaClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Consensa_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsensaServer is the server API for Consensa service.
// All implementations must embed UnimplementedConsensaServer
// for forward compatibility.
type ConsensaServer interface {
	Upsert(grpc.ClientStreamingServer[UpsertRequest, UpsertResponse]) error
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedConsensaServer()
}

// UnimplementedConsensaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsensaServer struct{}

func (UnimplementedConsensaServer) Upsert(grpc.ClientStreamingServer[UpsertRequest, UpsertResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedConsensaServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedConsensaServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConsensaServer) BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedConsensaServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedConsensaServer) mustEmbedUnimplementedConsensaServer() {}
func (UnimplementedConsensaServer) testEmbeddedByValue()                  {}

// UnsafeConsensaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsensaServer will
// result in compilation errors.
type UnsafeConsensaServer interface {
	mustEmbedUnimplementedConsensaServer()
}

func RegisterConsensaServer(s grpc.ServiceRegistrar, srv ConsensaServer) {
	// If the following call pancis, it indicates UnimplementedConsensaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Consensa_ServiceDesc, srv)
}

func _Consensa_Upsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsensaServer).Upsert(&grpc.GenericServerStream[UpsertRequest, UpsertResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consensa_UpsertServer = grpc.ClientStreamingServer[UpsertRequest, UpsertResponse]

func _Consensa_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsensaServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consensa_SearchServer = grpc.ServerStreamingServer[SearchResult]

func _Consensa_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consensa_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensaServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensa_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensaServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consensa_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensaServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consensa_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensaServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consensa_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensaServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Consensa_ServiceDesc is the grpc.ServiceDesc for Consensa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consensa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensa.v1.Consensa",
	HandlerType: (*ConsensaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _Consensa_Delete_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _Consensa_BatchGet_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Consensa_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upsert",
			Handler:       _Consensa_Upsert_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _Consensa_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/consensa/v1/consensa.proto",
}

const (
	ConsensaKV_TransactionalPut_FullMethodName = "/consensa.v1.ConsensaKV/TransactionalPut"
)

// ConsensaKVClient is the client API for ConsensaKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConsensaKV is a separate service from Consensa (the vector-index plane) on purpose: it
// exposes internal/txn's cross-range 2PC coordinator, which has nothing to do with the
// HNSW Index a Consensa server wraps. See internal/server/kv_service.go's doc comment for
// the full reasoning and what this deliberately does not yet cover (single-key writes,
// reads, and the DurableRange-per-range assembly are the caller's job today).
type ConsensaKVClient interface {
	TransactionalPut(ctx context.Context, in *TransactionalPutRequest, opts ...grpc.CallOption) (*TransactionalPutResponse, error)
}

type consensaKVClient struct {
	cc grpc.ClientConnInterface
}

func NewConsensaKVClient(cc grpc.ClientConnInterface) ConsensaKVClient {
	return &consensaKVClient{cc}
}

func (c *consensaKVClient) TransactionalPut(ctx context.Context, in *TransactionalPutRequest, opts ...grpc.CallOption) (*TransactionalPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionalPutResponse)
	err := c.cc.Invoke(ctx, ConsensaKV_TransactionalPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsensaKVServer is the server API for ConsensaKV service.
// All implementations must embed UnimplementedConsensaKVServer
// for forward compatibility.
//
// ConsensaKV is a separate service from Consensa (the vector-index plane) on purpose: it
// exposes internal/txn's cross-range 2PC coordinator, which has nothing to do with the
// HNSW Index a Consensa server wraps. See internal/server/kv_service.go's doc comment for
// the full reasoning and what this deliberately does not yet cover (single-key writes,
// reads, and the DurableRange-per-range assembly are the caller's job today).
type ConsensaKVServer interface {
	TransactionalPut(context.Context, *TransactionalPutRequest) (*TransactionalPutResponse, error)
	mustEmbedUnimplementedConsensaKVServer()
}

// UnimplementedConsensaKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsensaKVServer struct{}

func (UnimplementedConsensaKVServer) TransactionalPut(context.Context, *TransactionalPutRequest) (*TransactionalPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionalPut not implemented")
}
func (UnimplementedConsensaKVServer) mustEmbedUnimplementedConsensaKVServer() {}
func (UnimplementedConsensaKVServer) testEmbeddedByValue()                    {}

// UnsafeConsensaKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsensaKVServer will
// result in compilation errors.
type UnsafeConsensaKVServer interface {
	mustEmbedUnimplementedConsensaKVServer()
}

func RegisterConsensaKVServer(s grpc.ServiceRegistrar, srv ConsensaKVServer) {
	// If the following call pancis, it indicates UnimplementedConsensaKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsensaKV_ServiceDesc, srv)
}

func _ConsensaKV_TransactionalPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionalPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensaKVServer).TransactionalPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensaKV_TransactionalPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensaKVServer).TransactionalPut(ctx, req.(*TransactionalPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsensaKV_ServiceDesc is the grpc.ServiceDesc for ConsensaKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsensaKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensa.v1.ConsensaKV",
	HandlerType: (*ConsensaKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransactionalPut",
			Handler:    _ConsensaKV_TransactionalPut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/consensa/v1/consensa.proto",
}
